### PR TITLE
KOGITO-862: Fixing compilation issues after ResourceContent API changed.

### PR DESCRIPTION
**Pull request by romartin**
Hey @jesuino @ederign @porcelli @manstis 

Actual master upstream is broken after merging https://github.com/kiegroup/appformer/pull/886. Here are the fixes to make this repo compile again.

Can you please quickly review and merge, if so? I think that's urgent because master doesn't compile, at least for me.

PS: Please guys next time check the downstream builds are green before merging. I don't see the downstream build green for https://github.com/kiegroup/appformer/pull/886, and it's expected it should be running into this compile issue as well, as it's a compilation error. Anyway, just for the records, lemme know if I can help on any other thing! :+1: 

Thanks in advance!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@romartin sorry for it, it was my bad.

And thanks for the quick fix.

**Comment by jesuino** [comment]
thank you @romartin
